server:
  port: 9999


spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/netology?user=postgres&password=228488432}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  main:
    allow-circular-references: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  token:
    secret: "secret"
    expiration: 180000

cors:
  origins: 'http://localhost:8080'
  methods: '*'
  headers: '*'
  credentials: true
